SedmiProjekt/Controllers/AlbumiController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SedmiProjekt.Models;

namespace SedmiProjekt.Controllers
{
    public class AlbumiController : Controller
    {
        private readonly IRepozitorijUpiti _repozitorij;
        public AlbumiController(IRepozitorijUpiti repozitorij)
        {
            _repozitorij = repozitorij;
        }

        public IActionResult Index()
        {
            return View(_repozitorij.PopisAlbuma());
        }

        public IActionResult Create()
        {
            ViewData["ZanrId"] = new SelectList(_repozitorij.PopisZanrova(), "Id", "Naziv");
            int sljedeciId = _repozitorij.SljedeciId();
            Albumi albumi = new Albumi() { Id = sljedeciId };
            return View(albumi);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Id,Izvodac, Album, Cijena, Datum, SlikaUrl, ZanrId")] Albumi albumi)
        {
            ModelState.Remove("Zanr");//uklanjanje veze

            if (ModelState.IsValid)
            {
                _repozitorij.Create(albumi);
                return RedirectToAction("Index"); // ako je sve ok, tu završava metoda 
            }
            //ako je doslo do greške sljedeci dio se izvrsava
            ViewData["ZanrId"] = new SelectList(_repozitorij.PopisZanrova(), "Id", "Naziv", albumi.ZanrId);
            return View(albumi);

        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            if (id < 1)
            {
                return NotFound();
            }

            Albumi albumi= _repozitorij.DohvatiAlbumSaIdom(id);

            if (albumi == null) { return NotFound(); }

            ViewData["ZanrId"] = new SelectList(_repozitorij.PopisZanrova(), "Id", "Naziv", albumi.ZanrId);
            return View(albumi);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(int id, [Bind("Id, Izvodac, Album, Cijena, Datum, SlikaUrl, ZanrId")] Albumi albumi)
        {
            if (id != albumi.Id)
            {
                return NotFound();
            }

            ModelState.Remove("Zanr");

            if (ModelState.IsValid)
            {
                _repozitorij.Update(albumi);
                return RedirectToAction("Index");
            }
            //ako je doslo do greške sljedeci dio se izvrsava
            ViewData["ZanrId"] = new SelectList(_repozitorij.PopisZanrova(), "Id", "Naziv", albumi.ZanrId);
            return View(albumi);

        }
        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id < 1)
            {
                return NotFound();
            }

            var albumi = _repozitorij.DohvatiAlbumSaIdom(Convert.ToInt16(id));

            if (albumi == null)
            {
                return NotFound();
            }

            return View(albumi);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            var album = _repozitorij.DohvatiAlbumSaIdom(id);
            _repozitorij.Delete(album);
            return RedirectToAction("Index");

        }

        public ActionResult SearchIndex(string albumZanr, string searchString)
        {
            var zanr = new List<string>();

            var zanrUpit = _repozitorij.PopisZanrova();

            ViewData["albumZanr"] = new SelectList(_repozitorij.PopisZanrova(), "Naziv", "Naziv", zanrUpit);

            var albumi = _repozitorij.PopisAlbuma();

            if (!String.IsNullOrWhiteSpace(searchString))
            {
                albumi = albumi.Where(s => s.Album.Contains(searchString, StringComparison.OrdinalIgnoreCase)); // StringComparison.OrdinalIgnoreCase ignorira velika-mala slova 
            }

            if (string.IsNullOrWhiteSpace(albumZanr))
                return View(albumi);
            else
            {
                return View(albumi.Where(x => x.Zanr.Naziv == albumZanr));
            }

        }



    }
}

SedmiProjekt/Controllers/ZanrController.cs
using Microsoft.AspNetCore.Mvc;
using SedmiProjekt.Models;

namespace SedmiProjekt.Controllers
{
    public class ZanrController : Controller
    {
        private readonly IRepozitorijUpiti _repozitorij;
            public ZanrController(IRepozitorijUpiti repozitorij)
            {
                _repozitorij= repozitorij;
            }

            public IActionResult Index()
            {
                return View(_repozitorij.PopisZanrova());
            }

            public IActionResult Create()
            {

                int sljedeciId = _repozitorij.ZanrSljedeciId(); // ova metoda je dodana i u repozitorij, zaboravio na nju
                Zanr zanr = new Zanr() { Id = sljedeciId };
                return View(zanr);
            }

            [HttpPost]
            [ValidateAntiForgeryToken]
            public IActionResult Create([Bind("Id,Naziv")] Zanr zanr)
            {
                ModelState.Remove("Albums");//uklanjanje veze

                if (ModelState.IsValid)
                {
                    _repozitorij.Create(zanr);
                    return RedirectToAction("Index"); // ako je sve ok, tu završava metoda 
                }
                //ako je doslo do greške sljedeci dio se izvrsava
                return View(zanr);

            }

            [HttpGet]
            public IActionResult Update(int? id)
            {
                if (id == null)
                {
                    return NotFound();
                }
                var zanr = _repozitorij.DohvatiZanrSaIdom(Convert.ToInt32(id));
                if (zanr == null)
                {
                    return NotFound();
                }
                return View(zanr);
            }

            [HttpPost]
            [ValidateAntiForgeryToken]
            public IActionResult Update(int id, [Bind("Id,Naziv")] Zanr zanr)
            {
                if (id != zanr.Id)
                {
                    return NotFound();
                }

                ModelState.Remove("Albums");//uklanjanje veze

                if (ModelState.IsValid)
                {
                    _repozitorij.Update(zanr);
                    return RedirectToAction("Index");
                }
                return View(zanr);
            }

            [HttpGet]
            public IActionResult Delete(int? id)
            {
                if (id == null)
                {
                    return NotFound();
                }
                var zanr = _repozitorij.DohvatiZanrSaIdom(Convert.ToInt32(id));
                if (zanr == null)
                {
                    return NotFound();
                }
                return View(zanr);
            }


            [HttpPost]
            public IActionResult Delete(int id)
            {
                var zanr = _repozitorij.DohvatiZanrSaIdom(Convert.ToInt32(id));
                _repozitorij.Delete(zanr);
                return RedirectToAction("Index");
            }
        }
    }

SedmiProjekt/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SedmiProjekt</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SedmiProjekt.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SedmiProjekt</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Početna stranica</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">O aplikaciji</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Albumi" asp-action="SearchIndex">Tražilica albuma</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Albumi" asp-action="Index">Popis albuma</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Zanr" asp-action="Index">Popis žanrova</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - SedmiProjekt - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>